apiVersion: v1
kind: ConfigMap
metadata:
  name: jiva-cm
  namespace: flux-system
data:
  values.yaml: |
    localpv-provisioner:
      # Disable installation of node-disk-manager components by default
      openebsNDM:
        enabled: false
      # Disable openebs-device deviceClass by default.
      deviceClass:
        enabled: false
      hostpathClass:
        reclaimPolicy: Retain

      localpv:
        basePath: "/data/volumes"
    storageClass:
      isDefaultClass: true
      reclaimPolicy: Retain

    defaultPolicy:
      # Name of the default default JivaVolumePolicy
      name: openebs-jiva-default-policy
      # If true, enables creation of the openebs-jiva-default-policy JivaVolumePolicy
      enabled: true
      # replicaSC represents the storage class used for creating
      # the pvc for the replica sts provisioned by localpv provisioner
      replicaSC: openebs-hostpath
      # replicas represent the desired replication factor for the jiva volume
      replicas: 3
