apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox
    zarf.dev/agent: ignore
  name: busybox
  namespace: nextcloud
spec:
  # specifically assigning to node manually - update to dynamic in future orchestration
  containers:
  # replace sleep with a full rsync command
  - args:
    - sleep
    - "3600"
    image: busybox:latest
    imagePullPolicy: Always
    name: busybox
    resources: {}
    volumeMounts:
    - name: data-vol
      mountPath: /data
  volumes:
  - name: data-vol
    persistentVolumeClaim:
      claimName: pvc-11e12470-7738-48b1-bd1c-dbd9e504553c
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}