apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: test
  name: test
  namespace: test
spec:
  nodeSelector:
    storage: large
  containers:
  - image: busybox:latest
    name: test
    resources: {}
    command:
    - sleep
    - "3600"
    volumeMounts:
    - mountPath: /tmp/busy
      name: storage
  volumes:
  - name: storage
    persistentVolumeClaim:
      claimName: backend-claim
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
