apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-claim
  namespace: test
spec:
  storageClassName: "nfs-client"
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi