domain: infra.kellerhome.us

monitoring:
  enabled: true

loki:
  enabled: true
  strategy: monolith

promtail:
  enabled: true

kyverno:
  enabled: true

kyvernopolicies:
  enabled: true
  values:
    resources:
        limits:
          memory: 1024Mi
        requests:
          memory: 1024Mi
    policies:
      restrict-image-registries:
        exclude:
            any:
            - resources:
                namespaces:
                - openebs
                - nextcloud
        validationFailureAction: audit
        parameters:
          allow:
          - registry1.dso.mil
          - registry.dso.mil
          - nextcloud
          - bitnami
          - docker.io
      disallow-image-tags:
        exclude:
            any:
            - resources:
                namespaces:
                - valheim

      disallow-shared-subpath-volume-writes:
        exclude:
            any:
            - resources:
                namespaces:
                - valheim

      disallow-privileged-containers:
        exclude:
            any:
            - resources:
                namespaces:
                - openebs

      disallow-host-namespaces:
        exclude:
            any:
            - resources:
                namespaces:
                - openebs

      disallow-privilege-escalation:
        exclude:
            any:
            - resources:
                namespaces:
                - openebs

      require-non-root-group:
        exclude:
            any:
            - resources:
                namespaces:
                - openebs
                - nextcloud

      require-non-root-user:
        exclude:
            any:
            - resources:
                namespaces:
                - openebs
                - nextcloud
      
      restrict-host-path-mount:
        exclude:
            any:
            - resources:
                namespaces:
                - openebs

      restrict-host-path-write:
        exclude:
            any:
            - resources:
                namespaces:
                - openebs
                - nextcloud

      restrict-volume-types:
        exclude:
            any:
            - resources:
                namespaces:
                - openebs

neuvector:
  enabled: true

addons:
  metricsServer:
    enabled: true