apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rollout-restart-role
  namespace: blog
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "patch"]
