apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rollout-restart-rolebinding
  namespace: blog
subjects:
- kind: ServiceAccount
  name: rollout-restart-sa
  namespace: blog
roleRef:
  kind: Role
  name: rollout-restart-role
  apiGroup: rbac.authorization.k8s.io
