kind: ZarfPackageConfig
metadata:
  name: home-automation
  description: "Components comprising my home automation orchestration"
  version: 0.0.9
  architecture: amd64

variables:
  - name: VIP_INTERFACE
    description: "Interface for the VIP"
    prompt: true
    sensitive: false
  - name: VIP_ADDRESS
    description: "IP address for the VIP"
    prompt: true
    sensitive: false
  - name: VIP_IP_RANGE
    description: "Range of ip addresses for loadbalancers 192.168.0.12-192.168.0.13"
    prompt: true
    sensitive: false
  - name: CERT_EMAIL
    description: "certificate email for requesting letsencrypt cert"
    prompt: true
    sensitive: false
  - name: DNS_ZONE
    description: "DNS zone for certificate issuing"
    prompt: true
    sensitive: false
  - name: SECRET_ACCESS_KEY
    description: "Secret access key for cert-manager aws access"
    prompt: true
    sensitive: true
  - name: ACCESS_KEY
    description: "Access key for cert-manager aws access"
    prompt: true
    sensitive: true


components:
  - name: image-seed
    images:
    - ghcr.io/kube-vip/kube-vip:v0.6.2
    - ghcr.io/kube-vip/kube-vip-cloud-provider:v0.0.7
    - quay.io/jetstack/cert-manager-controller:v1.12.1
    - quay.io/jetstack/cert-manager-webhook:v1.12.1
    - quay.io/jetstack/cert-manager-cainjector:v1.12.1
    - quay.io/jetstack/cert-manager-acmesolver:v1.12.1
    - quay.io/jetstack/cert-manager-ctl:v1.12.1
    - registry1.dso.mil/ironbank/opensource/istio/operator:1.18.2
    - registry1.dso.mil/ironbank/big-bang/base:2.0.0
    - registry1.dso.mil/ironbank/opensource/istio/pilot:1.18.2
    - registry1.dso.mil/ironbank/opensource/istio/proxyv2:1.18.2
    - registry1.dso.mil/ironbank/opensource/istio/install-cni:1.18.2

  - name: kube-vip
    manifests:
    - name: kube-vip
      namespace: kube-vip
      files:
      - configs/kubevip/rbac.yaml
      - configs/kubevip/daemonset.yaml
      - configs/kubevip/kube-vip-cloud-controller.yaml
    - name: kube-vip-config
      files:
      - configs/kubevip/kube-vip-cloud-configmap.yaml


  - name: cert-manager-chart
    manifests:
    - name: cert-manager
      files:
      - configs/cert-manager/namespace.yaml
    charts:
      - name: cert-manager
        namespace: cert-manager
        url: https://charts.jetstack.io
        version: v1.12.1
        valuesFiles:
          - configs/cert-manager/values.yaml
  
  - name: cert-manager-addons
    manifests:
    - name: cert-manager-addons
      namespace: cert-manager
      files:
      - configs/cert-manager/secret.yaml
      - configs/cert-manager/cluster-issuer.yaml
      - configs/cert-manager/selfsigned-cluster-issuer.yaml
      - configs/cert-manager/ca-cert.yaml
      - configs/cert-manager/ca-issuer.yaml

  - name: istio-operator
    charts:
    - name: istio-operator
      version: 1.18.2-bb.0
      namespace: istio-operator
      url: https://repo1.dso.mil/big-bang/product/packages/istio-operator.git@1.18.2-bb.0
      gitPath: chart/
      valuesFiles:
      - configs/istio-operator/values.yaml

  - name: istio-controlplane
    charts:
    - name: istio
      version: 1.18.2-bb.1
      namespace: istio-system
      url: https://repo1.dso.mil/big-bang/product/packages/istio-controlplane.git@1.18.2-bb.1
      gitPath: chart/
      valuesFiles:
      - configs/istio/values.yaml
    manifests:
    - name: istio-gateway-cert
      namespace: istio-system
      files:
        - configs/istio/certificate.yaml
