apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: test-dns
  namespace: default
spec:
  selector:
    matchLabels:
      name: test-dns
  template:
    metadata:
      labels:
        name: test-dns
    spec:
      containers:
      - name: coredns
        image: rancher/hardened-coredns:v1.9.3-build20220613
        args:
        - -conf
        - /etc/coredns/Corefile
        ports:
        - containerPort: 53
          hostPort: 53
          protocol: UDP
        volumeMounts:
        - mountPath: /etc/coredns
          name: config-volume
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: Corefile
            path: Corefile
          - key: dns.db
            path: dns.db
          name: dnsfiles
        name: config-volume

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dnsfiles
  namespace: 
data:

  Corefile: |
    kellerhome.us:53 {
        file /etc/coredns/dns.db
        log
        errors
    }

    .:53 {
        forward . 8.8.8.8 9.9.9.9
        log
        errors
    }

  dns.db: |
    kellerhome.us.        IN  SOA dns.kellerhome.us. keller.kellerhome.us. 2015082541 7200 3600 1209600 3600
    router.kellerhome.us.       IN  A  192.168.0.1
    k8s.kellerhome.us.          IN  A  192.168.1.20
    *.k8s.kellerhome.us.        IN  A  192.168.1.20
    manage.kellerhome.us.          IN  A  192.168.0.130
  