apiVersion: v1
kind: Pod
metadata:
  annotations:
    checksum/config: 1a569f42e377e4df052c3f07f5ac7e69ed3764da7b83036e29bda2f344dffc0c
    cni.projectcalico.org/containerID: 21a26883651b0153dfaa417dad931a8d3ec101365a703caf7bb3461a2a1b0c00
    cni.projectcalico.org/podIP: 10.42.0.3/32
    cni.projectcalico.org/podIPs: 10.42.0.3/32
    kubernetes.io/psp: global-unrestricted-psp
    scheduler.alpha.kubernetes.io/critical-pod: ""
  creationTimestamp: "2022-08-21T02:47:33Z"
  generateName: rke2-coredns-rke2-coredns-76cb76d66-
  labels:
    app.kubernetes.io/instance: rke2-coredns
    app.kubernetes.io/name: rke2-coredns
    k8s-app: kube-dns
    pod-template-hash: 76cb76d66
  name: rke2-coredns-rke2-coredns-76cb76d66-hk4zq
  namespace: kube-system
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: rke2-coredns-rke2-coredns-76cb76d66
    uid: e4b5c9c7-7ae5-4b6d-9bbb-23946d5dbc3f
  resourceVersion: "764"
  uid: 08898026-495e-4176-8ae7-06d717d943d8
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: k8s-app
            operator: In
            values:
            - kube-dns
        topologyKey: kubernetes.io/hostname
  containers:
  - args:
    - -conf
    - /etc/coredns/Corefile
    image: rancher/hardened-coredns:v1.9.3-build20220613
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 5
      httpGet:
        path: /health
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 60
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    name: coredns
    ports:
    - containerPort: 53
      name: udp-53
      protocol: UDP
    - containerPort: 53
      name: tcp-53
      protocol: TCP
    readinessProbe:
      failureThreshold: 5
      httpGet:
        path: /ready
        port: 8181
        scheme: HTTP
      initialDelaySeconds: 30
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/coredns
      name: config-volume
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-wd29g
      readOnly: true
  dnsPolicy: Default
  enableServiceLinks: true
  nodeName: rke2-server-01
  nodeSelector:
    kubernetes.io/os: linux
  preemptionPolicy: PreemptLowerPriority
  priority: 2000000000
  priorityClassName: system-cluster-critical
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: coredns
  serviceAccountName: coredns
  terminationGracePeriodSeconds: 30
  tolerations:
  - key: CriticalAddonsOnly
    operator: Exists
  - effect: NoSchedule
    key: node-role.kubernetes.io/control-plane
    operator: Exists
  - effect: NoExecute
    key: node-role.kubernetes.io/etcd
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - configMap:
      defaultMode: 420
      items:
      - key: Corefile
        path: Corefile
      name: rke2-coredns-rke2-coredns
    name: config-volume
  - name: kube-api-access-wd29g
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2022-08-21T02:47:43Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2022-08-21T02:48:23Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2022-08-21T02:48:23Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2022-08-21T02:47:43Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://ffad1ff9e228079d230dedfa0fa0e835bc9abc8f28832eb815f3893f733ed846
    image: docker.io/rancher/hardened-coredns:v1.9.3-build20220613
    imageID: sha256:491a6519673bdf1c71a0652525e045eda85f4f89589abc1d0f1748ed09860381
    lastState: {}
    name: coredns
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2022-08-21T02:47:46Z"
  hostIP: 192.168.1.20
  phase: Running
  podIP: 10.42.0.3
  podIPs:
  - ip: 10.42.0.3
  qosClass: Guaranteed
  startTime: "2022-08-21T02:47:43Z"
