domain: prod.kellerhome.us

istio:
  git:
    repo: https://repo1.dso.mil/platform-one/big-bang/apps/core/istio-controlplane.git
    tag: "1.17.2-bb.1"
    path: "./chart"
  enabled: true

istioOperator:
  git:
    repo: https://repo1.dso.mil/platform-one/big-bang/apps/core/istio-operator.git
    tag: "1.17.2-bb.1"
    path: "./chart"
  enabled: true

monitoring:
  git:
    repo: https://repo1.dso.mil/platform-one/big-bang/apps/core/monitoring.git
    tag: "43.1.2-bb.5"
    path: "./chart"
  enabled: true

loki:
  git:
    repo: https://repo1.dso.mil/platform-one/big-bang/apps/sandbox/loki.git
    tag: "5.0.0-bb.3"
    path: "./chart"
  enabled: true
  strategy: monolith

promtail:
  git:
    repo: https://repo1.dso.mil/platform-one/big-bang/apps/sandbox/promtail.git
    tag: "6.11.0-bb.0"
    path: "./chart"
  enabled: true

kyverno:
  git:
    repo: https://repo1.dso.mil/platform-one/big-bang/apps/sandbox/kyverno.git
    tag: "2.7.2-bb.0"
    path: "./chart"
  enabled: true

kyvernoPolicies:
  git:
    repo: https://repo1.dso.mil/platform-one/big-bang/apps/sandbox/kyverno-policies.git
    tag: "1.1.0-bb.6"
    path: "./chart"
  enabled: true
  values:
    resources:
        limits:
          memory: 1024Mi
        requests:
          memory: 1024Mi
    policies:
      restrict-image-registries:
        exclude:
            any:
            - resources:
                namespaces:
                - longhorn
                - nextcloud
        validationFailureAction: audit
        parameters:
          allow:
          - registry1.dso.mil
          - nextcloud
          - bitnami
          - docker.io
          - registry.k8s.io
          - cgr.dev

      disallow-image-tags:
        exclude:
            any:
            - resources:  
                namespaces:
                - valheim
                - wger

      disallow-shared-subpath-volume-writes:
        exclude:
            any:
            - resources:
                namespaces:
                - valheim

      disallow-privileged-containers:
        exclude:
            any:
            - resources:
                namespaces:
                - longhorn

      disallow-host-namespaces:
        exclude:
            any:
            - resources:
                namespaces:
                - longhorn

      disallow-privilege-escalation:
        exclude:
            any:
            - resources:
                namespaces:
                - longhorn

      require-non-root-group:
        exclude:
            any:
            - resources:
                namespaces:
                - longhorn
                - nextcloud

      require-non-root-user:
        exclude:
            any:
            - resources:
                namespaces:
                - longhorn
                - nextcloud
      
      # restrict-host-path-mount:
      #   exclude:
      #       any:
      #       - resources:
      #           namespaces:
      #           - openebs

      restrict-host-path-write:
        exclude:
            any:
            - resources:
                namespaces:
                - longhorn
                - nextcloud

      restrict-volume-types:
        exclude:
            any:
            - resources:
                namespaces:
                - nfs
                - longhorn

neuvector:
  git:
    repo: https://repo1.dso.mil/platform-one/big-bang/apps/sandbox/neuvector.git
    tag: "2.4.3-bb.0"
    path: "./chart"
  enabled: true
  values:
    k3s:
      enabled: true


addons:
  metricsServer:
    git:
      repo: https://repo1.dso.mil/platform-one/big-bang/apps/sandbox/metrics-server.git
      tag: "3.9.0-bb.1"
      path: "./chart"
    enabled: true

# helmRepositories:
#   - name: "bitnami"
#     repository: "oci://registry-1.docker.io/bitnamicharts"
#     existingSecret: ""
#     username: ""
#     password: ""
#     email: ""


wrapper:
  git:
    repo: https://repo1.dso.mil/big-bang/product/packages/wrapper.git
    tag: "0.4.0"
    path: "./chart"

packages:
  podinfo:
    enabled: true
    wrapper:
      enabled: true
    git:
      repo: https://github.com/stefanprodan/podinfo.git
      tag: 6.3.4
      path: charts/podinfo
    istio:
      hosts:
        - domain: "k8s.kellerhome.us"
          names:
            - podinfo
          gateways:
            - exposed
          destination:
            port: 9898
  renovate:
    git:
      repo: https://repo1.dso.mil/big-bang/product/packages/renovate.git
      tag: "34.120.0-bb.1"
      path: "./chart"
    enabled: true
    wrapper:
      enabled: false
    values:
      networkPolicies:
        enabled: "{{ $.Values.networkPolicies.enabled }}"
      istio:
        enabled: "{{ $.Values.istio.enabled }}"
      cronjob:
        schedule: '0 7 * * *'
  nextcloud:
    git:
      repo: https://github.com/nextcloud/helm.git
      tag: "nextcloud-3.5.4"
      path: "./charts/nextcloud"
    enabled: true
    wrapper:
      enabled: true
    network:
      policies: false
    istio:
      injection: "enabled"
      peerAuthentications: 
      # https://github.com/nextcloud/helm/issues/383
      - name: permissive-db
        spec:
          selector:
            matchLabels:
              app.kubernetes.io/instance: nextcloud
          mtls:
            mode: STRICT
          portLevelMtls:
            5432:
              mode: PERMISSIVE
      hosts:
        - names:
            - cloud
          gateways:
            - public
          destination:
            service: nextcloud
            port: 8080
    values:
      nextcloud:
        host: cloud.prod.kellerhome.us
        configs:
          domains.config.php: |-
            <?php
            $CONFIG = array (
              'trusted_domains' =>
                array (
                0 => 'localhost',
                1 => 'cloud.prod.kellerhome.us',
                )
            );
          overwrite.config.php: |-
            <?php
            $CONFIG = array (
              'overwriteprotocol' => 'https',
            );
      livenessProbe:
        enabled: true
        initialDelaySeconds: 15
        periodSeconds: 30
        timeoutSeconds: 10
        failureThreshold: 5
        successThreshold: 1
      readinessProbe:
        enabled: true
        initialDelaySeconds: 10
        periodSeconds: 25
        timeoutSeconds: 10
        failureThreshold: 5
        successThreshold: 1
      redis:
        enabled: true
      
      postgresql:
        enabled: true
        primary:
          persistence:
            enabled: true

      internalDatabase:
        enabled: false

      externalDatabase:
        enabled: true

        ## Supported database engines: mysql or postgresql
        type: postgresql

        ## Database name
        database: nextcloud

      persistence:
        enabled: true
        accessMode: ReadWriteOnce
        size: 10Gi

        nextcloudData:
          enabled: true
          storageClass: "nfs-client"
          accessMode: ReadWriteOnce
          size: 400Gi

  haproxy:
    enabled: true
    wrapper:
      enabled: false
    git:
      repo: https://repo1.dso.mil/big-bang/product/packages/haproxy.git
      tag: "1.12.0-bb.0"
      path: "./chart"
    values:
      service:
        type: LoadBalancer
      config: |
        #---------------------------------------------------------------------
        # Global settings
        #---------------------------------------------------------------------
        global
            daemon
            user                haproxy
            group               haproxy
            log stdout format raw local0
            maxconn             50000
            #chroot              /var/lib/haproxy

        #---------------------------------------------------------------------
        # common defaults that all the 'listen' and 'backend' sections will
        # use if not designated in their block
        #---------------------------------------------------------------------
        defaults
            mode                 tcp
            option               tcplog
            log                  global
            option               dontlognull
            timeout connect      5000
            timeout client       50000
            timeout server       50000

        #---------------------------------------------------------------------
        # dedicated stats page
        #---------------------------------------------------------------------
        listen stats
            mode http
            bind :22222
            stats enable
            stats uri            /haproxy?stats
            stats realm          Haproxy\ Statistics
            stats auth           test:test123
            stats refresh        30s

        #---------------------------------------------------------------------
        # main frontend which proxys to the backends
        #---------------------------------------------------------------------
        frontend main_https_listen
            bind *:443
            mode                tcp
            option              tcplog
            log                 global
            tcp-request inspect-delay 5s
            tcp-request content accept if { req.ssl_hello_type 1 }

        #---------------------------------------------------------------------
        # Common HAProxy nodes configuration
        #---------------------------------------------------------------------

        # -------------------------------
        # ACLs
        # -------------------------------

        # acl acl_MISSION      req.ssl_sni -i *.missionfocused.dev
        # acl acl_KUBE_KH      req.ssl_sni -i *.k8s.kellerhome.us
        acl acl_KUBE_KH req.ssl_sni -m end .k8s.kellerhome.us

        # -------------------------------
        # Conditions
        # -------------------------------

        # use_backend backend_MISSION if acl_MISSION
        use_backend backend_KUBE_KH if acl_KUBE_KH

        #---------------------------------------------------------------------
        # Backends
        #---------------------------------------------------------------------

        # MISSION
        # backend backend_MISSION
        #     description MISSION
        #     mode tcp
        #     balance source
        #     option ssl-hello-chk
        #     server server_MISSION mission-ingressgateway:443 check

        # PRODUCTION
        backend backend_KUBE_KH
            description PRODUCTION
            mode tcp
            balance source
            option tcp-check
            server server_PRODUCTION exposed-ingressgateway.istio-system.svc:443 check
