domain: prod.kellerhome.us

istio:
  git:
    repo: https://repo1.dso.mil/platform-one/big-bang/apps/core/istio-controlplane.git
    tag: "1.17.1-bb.0"
    path: "./chart"
  enabled: true

istiooperator:
  git:
    repo: https://repo1.dso.mil/platform-one/big-bang/apps/core/istio-operator.git
    tag: "1.17.1-bb.0"
    path: "./chart"
  enabled: true

monitoring:
  git:
    repo: https://repo1.dso.mil/platform-one/big-bang/apps/core/monitoring.git
    tag: "43.1.2-bb.4"
    path: "./chart"
  enabled: true

loki:
  git:
    repo: https://repo1.dso.mil/platform-one/big-bang/apps/sandbox/loki.git
    tag: "4.8.0-bb.0"
    path: "./chart"
  enabled: true
  strategy: monolith

promtail:
  git:
    repo: https://repo1.dso.mil/platform-one/big-bang/apps/sandbox/promtail.git
    tag: "6.8.1-bb.1"
    path: "./chart"
  enabled: true

kyverno:
    repo: https://repo1.dso.mil/platform-one/big-bang/apps/sandbox/kyverno.git
    tag: "2.6.5-bb.3"
    path: "./chart"
  enabled: true

kyvernopolicies:
  git:
    repo: https://repo1.dso.mil/platform-one/big-bang/apps/sandbox/kyverno-policies.git
    tag: "1.1.0-bb.3"
    path: "./chart"
  enabled: true
  values:
    resources:
        limits:
          memory: 1024Mi
        requests:
          memory: 1024Mi
    policies:
      restrict-image-registries:
        exclude:
            any:
            - resources:
                namespaces:
                - openebs
                - nextcloud
        validationFailureAction: audit
        parameters:
          allow:
          - registry1.dso.mil
          - registry.dso.mil
          - nextcloud
          - bitnami
          - docker.io
      disallow-image-tags:
        exclude:
            any:
            - resources:
                namespaces:
                - valheim
                - wger

      disallow-shared-subpath-volume-writes:
        exclude:
            any:
            - resources:
                namespaces:
                - valheim

      disallow-privileged-containers:
        exclude:
            any:
            - resources:
                namespaces:
                - openebs

      disallow-host-namespaces:
        exclude:
            any:
            - resources:
                namespaces:
                - openebs

      disallow-privilege-escalation:
        exclude:
            any:
            - resources:
                namespaces:
                - openebs

      require-non-root-group:
        exclude:
            any:
            - resources:
                namespaces:
                - openebs
                - nextcloud

      require-non-root-user:
        exclude:
            any:
            - resources:
                namespaces:
                - openebs
                - nextcloud
      
      restrict-host-path-mount:
        exclude:
            any:
            - resources:
                namespaces:
                - openebs

      restrict-host-path-write:
        exclude:
            any:
            - resources:
                namespaces:
                - openebs
                - nextcloud

      restrict-volume-types:
        exclude:
            any:
            - resources:
                namespaces:
                - openebs

neuvector:
  git:
    repo: https://repo1.dso.mil/platform-one/big-bang/apps/sandbox/neuvector.git
    tag: "2.4.2-bb.5"
    path: "./chart"
  enabled: true
  values:
    k3s:
      enabled: true


addons:
  metricsServer:
    git:
      repo: https://repo1.dso.mil/platform-one/big-bang/apps/sandbox/metrics-server.git
      tag: "3.8.4-bb.0"
      path: "./chart"
    enabled: true

# ociRepositories:
#   - name: "bitnami"
#     repository: "oci://registry-1.docker.io/bitnamicharts"
#     existingSecret: ""
#     username: ""
#     password: ""
#     email: ""


wrapper:
  git:
    repo: "https://repo1.dso.mil/big-bang/product/packages/wrapper.git"
    tag: "0.1.1"
    path: "./chart"

packages:
  podinfo:
    enabled: true
    wrapper:
      enabled: true
    git:
      repo: https://github.com/stefanprodan/podinfo.git
      tag: 6.3.4
      path: charts/podinfo
    istio:
      hosts:
        - domain: "k8s.kellerhome.us"
          names:
            - podinfo
          gateways:
            - exposed
          destination:
            port: 9898
  wger:
    enabled: false
    wrapper:
      enabled: true
    git:
      repo: https://github.com/wger-project/helm-charts.git
      tag: "wger-0.1.3"
      path: charts/wger
    network:
      policies: false
    istio:
      injection: false
      hosts:
        - domain: "k8s.kellerhome.us"
          names:
            - fitness
          gateways:
            - exposed
          destination:
            service: wger-http
            port: 8000


