domain: prod.kellerhome.us

istio:
  git:
    repo: https://repo1.dso.mil/platform-one/big-bang/apps/core/istio-controlplane.git
    tag: "1.17.1-bb.0"
    path: "./chart"
  enabled: true

istiooperator:
  git:
    repo: https://repo1.dso.mil/platform-one/big-bang/apps/core/istio-operator.git
    tag: "1.17.1-bb.0"
    path: "./chart"
  enabled: true

monitoring:
  git:
    repo: https://repo1.dso.mil/platform-one/big-bang/apps/core/monitoring.git
    tag: "43.1.2-bb.4"
    path: "./chart"
  enabled: true

loki:
  git:
    repo: https://repo1.dso.mil/platform-one/big-bang/apps/sandbox/loki.git
    tag: "4.8.0-bb.1"
    path: "./chart"
  enabled: true
  strategy: monolith

promtail:
  git:
    repo: https://repo1.dso.mil/platform-one/big-bang/apps/sandbox/promtail.git
    tag: "6.8.1-bb.1"
    path: "./chart"
  enabled: true

kyverno:
  git:
    repo: https://repo1.dso.mil/platform-one/big-bang/apps/sandbox/kyverno.git
    tag: "2.6.5-bb.3"
    path: "./chart"
  enabled: true

kyvernopolicies:
  git:
    repo: https://repo1.dso.mil/platform-one/big-bang/apps/sandbox/kyverno-policies.git
    tag: "1.1.0-bb.4"
    path: "./chart"
  enabled: true
  values:
    resources:
        limits:
          memory: 1024Mi
        requests:
          memory: 1024Mi
    policies:
      restrict-image-registries:
        exclude:
            any:
            - resources:
                namespaces:
                - longhorn
                - nextcloud
        validationFailureAction: audit
        parameters:
          allow:
          - registry1.dso.mil
          - registry.dso.mil
          - nextcloud
          - bitnami
          - docker.io
          - registry.k8s.io
      disallow-image-tags:
        exclude:
            any:
            - resources:
                namespaces:
                - valheim
                - wger

      disallow-shared-subpath-volume-writes:
        exclude:
            any:
            - resources:
                namespaces:
                - valheim

      disallow-privileged-containers:
        exclude:
            any:
            - resources:
                namespaces:
                - longhorn

      disallow-host-namespaces:
        exclude:
            any:
            - resources:
                namespaces:
                - longhorn

      disallow-privilege-escalation:
        exclude:
            any:
            - resources:
                namespaces:
                - longhorn

      require-non-root-group:
        exclude:
            any:
            - resources:
                namespaces:
                - longhorn
                - nextcloud

      require-non-root-user:
        exclude:
            any:
            - resources:
                namespaces:
                - longhorn
                - nextcloud
      
      # restrict-host-path-mount:
      #   exclude:
      #       any:
      #       - resources:
      #           namespaces:
      #           - openebs

      restrict-host-path-write:
        exclude:
            any:
            - resources:
                namespaces:
                - longhorn
                - nextcloud

      restrict-volume-types:
        exclude:
            any:
            - resources:
                namespaces:
                - nfs
                - longhorn

neuvector:
  git:
    repo: https://repo1.dso.mil/platform-one/big-bang/apps/sandbox/neuvector.git
    tag: "2.4.2-bb.5"
    path: "./chart"
  enabled: true
  values:
    k3s:
      enabled: true


addons:
  metricsServer:
    git:
      repo: https://repo1.dso.mil/platform-one/big-bang/apps/sandbox/metrics-server.git
      tag: "3.8.4-bb.0"
      path: "./chart"
    enabled: true

# ociRepositories:
#   - name: "bitnami"
#     repository: "oci://registry-1.docker.io/bitnamicharts"
#     existingSecret: ""
#     username: ""
#     password: ""
#     email: ""


wrapper:
  git:
    repo: https://repo1.dso.mil/big-bang/product/packages/wrapper.git
    tag: "0.1.1"
    path: "./chart"

packages:
  podinfo:
    enabled: true
    wrapper:
      enabled: true
    git:
      repo: https://github.com/stefanprodan/podinfo.git
      tag: 6.3.4
      path: charts/podinfo
    istio:
      hosts:
        - domain: "k8s.kellerhome.us"
          names:
            - podinfo
          gateways:
            - exposed
          destination:
            port: 9898
  renovate:
    git:
      repo: https://repo1.dso.mil/big-bang/product/packages/renovate.git
      tag: "34.120.0-bb.0"
      path: "./chart"
    enabled: true
    wrapper:
      enabled: false
    values:
      networkPolicies:
        enabled: "{{ $.Values.networkPolicies.enabled }}"
      istio:
        enabled: "{{ $.Values.istio.enabled }}"
      cronjob:
        schedule: '0 7 * * *'
  nextcloud:
    git:
      repo: https://github.com/nextcloud/helm.git
      tag: "nextcloud-3.5.4"
      path: "./charts/nextcloud"
    enabled: false
    wrapper:
      enabled: true
    network:
      policies: "{{ $.Values.networkPolicies.enabled }}"
    istio:
      injection: true
      hosts:
        - names:
            - cloud
          gateways:
            - public
          destination:
            service: nextcloud
            port: 8080
    values:
      nextcloud:
        host: cloud.prod.kellerhome.us
        configs:
          domains.config.php: |-
            <?php
            $CONFIG = array (
              'trusted_domains' =>
                array (
                0 => 'localhost',
                1 => 'cloud.prod.kellerhome.us',
                )
            );
          overwrite.config.php: |-
            <?php
            $CONFIG = array (
              'overwriteprotocol' => 'https',
            );
      livenessProbe:
        enabled: true
        initialDelaySeconds: 15
        periodSeconds: 30
        timeoutSeconds: 10
        failureThreshold: 5
        successThreshold: 1
      readinessProbe:
        enabled: true
        initialDelaySeconds: 10
        periodSeconds: 25
        timeoutSeconds: 10
        failureThreshold: 5
        successThreshold: 1
      redis:
        enabled: true
      
      postgresql:
        enabled: true
        primary:
          persistence:
            enabled: true

      internalDatabase:
        enabled: false

      externalDatabase:
        enabled: true

        ## Supported database engines: mysql or postgresql
        type: postgresql

        ## Database name
        database: nextcloud

      persistence:
        enabled: true
        accessMode: ReadWriteOnce
        size: 10Gi

        nextcloudData:
          enabled: true
          storageClass: "nfs-client"
          accessMode: ReadWriteOnce
          size: 400Gi


