bases:
- ../../../bases/bigbang
configMapGenerator:
  - name: environment
    behavior: merge
    files:
      - values.yaml=configmap.yaml
secretGenerator:
  - name: certs-bb
    namespace: bigbang
    behavior: create

patchesStrategicMerge:
## Enable the line below if a secrets.enc.yaml is created in this directory
- secrets.enc.yaml
- |-
  apiVersion: helm.toolkit.fluxcd.io/v2beta1
  kind: HelmRelease
  metadata:
    name: bigbang
  spec:
    valuesFrom:
      - kind: Secret
        name: common-bb
      - kind: ConfigMap
        name: common
      - kind: Secret
        name: environment-bb
      - kind: ConfigMap
        name: environment
      - kind: Secret
        name: certs-bb
