apiVersion: v1
data:
  default.conf: |-
    server {
        listen 8080;
        server_name brandtkeller.com www.brandtkeller.com;
        return 301 https://$host$request_uri;
    }

    server {
        listen 8080;
        server_name bekindchooseviolence.com www.bekindchooseviolence.com;
        return 301 https://$host$request_uri;
    }

    server {
        listen 8443 ssl http2;
        server_name brandtkeller.com www.brandtkeller.com;

        gzip on;
        gzip_comp_level 9;
        gzip_types
        text/html
        text/plain
        text/css
        text/js
        text/xml
        text/javascript
        application/javascript
        application/json
        application/xml
        application/rss+xml
        image/svg+xml;

        ssl_certificate /etc/nginx/ssl/site/tls.crt;
        ssl_certificate_key /etc/nginx/ssl/site/tls.key;
        ssl_session_timeout 5m;
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_prefer_server_ciphers off;

        root /site;

        location / {
            index index.html index.htm;
        }

        location ~* ^/([^/]+) {
            index index.html index.htm;
            error_page 404 = @error;
        }

        error_page 404 /404.html;
        location @error {
            try_files /$1/404.html /404.html =404;
        }
    }

    server {
        listen 8443 ssl http2;
        server_name bekindchooseviolence.com www.bekindchooseviolence.com;

        gzip on;
        gzip_comp_level 9;
        gzip_types
        text/html
        text/plain
        text/css
        text/js
        text/xml
        text/javascript
        application/javascript
        application/json
        application/xml
        application/rss+xml
        image/svg+xml;

        ssl_certificate /etc/nginx/ssl/bkcv/tls.crt;
        ssl_certificate_key /etc/nginx/ssl/bkcv/tls.key;
        ssl_session_timeout 5m;
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_prefer_server_ciphers off;

        root /site;

        location / {
            index index.html index.htm;
        }

        location ~* ^/([^/]+) {
            index index.html index.htm;
            error_page 404 = @error;
        }

        error_page 404 /404.html;
        location @error {
            try_files /$1/404.html /404.html =404;
        }
    }
kind: ConfigMap
metadata:
  name: nginx-conf
