apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: kube-api-dns-egress
  namespace: nextcloud
spec:
  podSelector: {}
  policyTypes:
  - Egress
  egress:
  - to:
    - namespaceSelector: {}
    ports:
    - port: 53
      protocol: UDP
