version: '3.5'

services:
  dns:
    restart: unless-stopped
    image: coredns/coredns:1.10.0
    command: -conf /etc/coredns/Corefile
    volumes:
      - "./config/dns:/etc/coredns"
    ports:
      - "53:53"
      - "53:53/udp"

  nfs:
    restart: unless-stopped
    image: itsthenetwork/nfs-server-alpine:latest
    privileged: true
    environment:
      - SHARED_DIRECTORY=/nfsshare
    volumes:
      - "/data/nfs:/nfsshare"
    ports:
      - "2049:2049"

  zwave:
    restart: unless-stopped
    image: zwavejs/zwave-js-ui:9.11.1
    environment:
      - SESSION_SECRET=mysupersecretkey
    ports:
      - "8091:8091"
      - "3000:3000"
    volumes:
      - "/dev/serial/by-id/usb-Silicon_Labs_CP2102N_USB_to_UART_Bridge_Controller_f0d36ebf3694eb118dec3a703d98b6d1-if00-port0:/dev/zwave"
      - "${HOME}/data/zwave:/usr/src/app/store"

  # unifi-db:
  #   image: docker.io/mongo:5.0.26
  #   container_name: unifi-db
  #   volumes:
  #     - /path/to/data:/data/db
  #     - /path/to/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
  #   restart: unless-stopped

  # unifi-network-application:
  #   image: lscr.io/linuxserver/unifi-network-application:latest
  #   container_name: unifi-network-application
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Etc/UTC
  #     - MONGO_USER=unifi
  #     - MONGO_PASS=
  #     - MONGO_HOST=unifi-db
  #     - MONGO_PORT=27017
  #     - MONGO_DBNAME=unifi
  #     - MEM_LIMIT=1024 #optional
  #     - MEM_STARTUP=1024 #optional
  #     - MONGO_TLS= #optional
  #     - MONGO_AUTHSOURCE= #optional
  #   volumes:
  #     - /path/to/unifi-network-application/data:/config
  #   ports:
  #     - 8443:8443
  #     - 3478:3478/udp
  #     - 10001:10001/udp
  #     - 8080:8080
  #     - 1900:1900/udp #optional
  #     - 8843:8843 #optional
  #     - 8880:8880 #optional
  #     - 6789:6789 #optional
  #     - 5514:5514/udp #optional
  #   restart: unless-stopped



  

