---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubevip
  namespace: kube-system
data:
  range-global: 192.168.1.21-192.168.1.23    # Range-based IP range for use in all namespaces
  range-valheim: 192.168.1.30-192.168.1.30