apiVersion: certmanager.k8s.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: ###ZARF_VAR_PRIVKEY_BASE64###
    privateKeySecretRef:
      name: letsencrypt
    dns01:
      providers:
      - name: route53
        route53:
          region: us-west-2
          accessKeyID: ###ZARF_VAR_PRIVKEY_BASE64###
          secretAccessKeySecretRef:
            name: aws-route53-creds
            key: password.txt