apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: ###ZARF_VAR_CERT_EMAIL###
    privateKeySecretRef:
      name: letsencrypt
    solvers:
    - selector:
        dnsZones:
          - "###ZARF_VAR_DNS_ZONE###"
      dns01:
        route53:
          region: us-west-2
          accessKeyID: ###ZARF_VAR_ACCESS_KEY###
          secretAccessKeySecretRef:
            name: aws-route53-creds
            key: secret-access-key