apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: bootstrap-lb
spec:
  selector:
    matchLabels:
      name: bootstrap-lb
  template:
    metadata:
      labels:
        name: bootstrap-lb
    spec:
      nodeSelector:
        node-role.kubernetes.io/master: "true"
      containers:
      - name: nginx
        image: nginx:1.23.1
        ports:
        - containerPort: 80
          hostPort: 80
          protocol: TCP
        - containerPort: 443
          hostPort: 443
          protocol: TCP
        volumeMounts:
        - mountPath: /etc/nginx
          name: config-volume
      volumes:
      - name: config-volume
        configMap:
          defaultMode: 420
          items:
          - key: nginx.conf
            path: nginx.conf
          name: loadbalancer-config
