kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: unifi-config-data
  labels:
    app.kubernetes.io/name: unifi-controller
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi