kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: unifi-config-data
  labels:
    app.kubernetes.io/name: unifi-controller
spec:
  storageClassName: "###ZARF_VAR_UNIFI_STORAGE_CLASS###"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi