apiVersion: v1
kind: Secret
metadata:
    name: aws-sec
    namespace: nextcloud
stringData:
    config: ENC[AES256_GCM,data:rJ/DTTgRIrczc7SWSMOql8M0R3ZTO1XSVgL64QVzvZfADInlnkHL/oqXqOcUeLg=,iv:phPj9sdDTZwdFs+RzblZOTxtNIHMQGiIEZ/dCvjh9FE=,tag:Wn2roUVT6aQR0cfDrxPmpw==,type:str]
    credentials: ENC[AES256_GCM,data:a+naDw1ev2idSZJ8c26tmjgvByY1KFBWL/5AO6CXepk1VvnL0mIaXsHKFg+RR0DqwvbOPlGG1Q==,iv:1wAH2u/vO/QhJoF5a7Bx7bonLeWZO8ueA9CxEhSoUNM=,tag:hO6fC1Y/6Sre7TAqGM7ERw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-12-31T03:50:36Z"
    mac: ENC[AES256_GCM,data:p/WbYCnXHpOgE+YM/pz9MWlK89402Gf9NiEEeLa8lRmtEKfpzBbKk9133DUHoBIC7cghB+XyZcPEvjP8zNzArw7SrOLoQ/ADijQwthze4mAsLYjQCtveoLcqX6R6Z1+v/80Wqhu48OLDkhbL1ewxbZAb6kS3Ld0OPgZHnbellD4=,iv:WEAiSyHfTqvvWxHeaOr0VyHhWiBa0tlMUrobdxD7qoA=,tag:beKsmf17sjPcnRnrE7ny2g==,type:str]
    pgp:
        - created_at: "2022-12-31T03:50:35Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA1pyIBzTsoKaAQ/9H6CwU8XB8xTvy3XE8Vc+zgCMf1QlzH0GNUg0kjZqDA6U
            cKDhi0JdcjIOOF27Dlqtvirp1vJyXBwmd6n7qtCfHPW8OvGv00QJ23BSLpfULX/J
            MyK+cec+ZBChPI2FAK27q8pXnovh0ENv9DNSVGrKfkN4rOue2e2Ivh8hlAnuHrT0
            /BATQCHdcb7U36xeUa3SvFUX89FWl1psYVmS3gHbyii+R1mpIxEH2ZKZXQNjfoat
            JYAvxyjIXI/9LL38C8D6A24FkvaeRktZIrOYpY3qiybVXNij1o0T3a4gnPtCcHHX
            MIAF82DKsjsHfM/MZobUNsHyRV8dyVtuPdPVJBzcTrYKNq1rotmxw3Uz4FZgmEmf
            mcf4qycjmrv50DYN2vycU7AI3wD8GwVc2tCE0wTvB18xhYAe4sYTbyMI+0sp7qC2
            enbJc4bBCRcTRRhglj3k/45nuvlhPiHwJAcTIDDFIcy99O9COOYv5nY3jl2+fg7A
            hGOlQzQW8ZcW5n4jFGWJXcKWDo/bo+vDV6ri1dRWQiyVnzFAmbTE2cPQYhai6DKa
            QGpU5pL8KjgPg9FJBkG9TL/GMh2NosV2Jx3iEUQIgJhmskJa9c6GJ1UEpA8+7fNc
            aftSH09N1wVkCebkIIIrErGazqpp41YeNmPN+LL1LECPKNQiiwSjXzhOWi8BFarS
            XAHn6bx/E/Qxg3G6WuLdoetK9HIvfpqaoVgqiDaQTqzb4g+ea0iMVbcp27KtL0qO
            x5LAsnNHHrZxmAFyCCukVXSresEwP79qSInS9IVKpIW3qCV1RMu29sLOM+j2
            =OEmN
            -----END PGP MESSAGE-----
          fp: BA7A548FFD17E767752D71D7D1415DC3F01E3E5F
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
