kind: ZarfPackageConfig
metadata:
  name: home-automation-flux
  description: "flux package for home automation orchestration"
  version: 0.0.1
components:
  - name: flux
    required: true
    manifests:
      - name: flux-installer
        # This will be built on the package create side and deployed as a regular manifest on package deploy
        kustomizations:
          - https://repo1.dso.mil/platform-one/big-bang/bigbang.git//base/flux?ref=2.2.0
    images:
      - registry1.dso.mil/ironbank/fluxcd/helm-controller:v0.32.1
      - registry1.dso.mil/ironbank/fluxcd/kustomize-controller:v0.35.1
      - registry1.dso.mil/ironbank/fluxcd/notification-controller:v0.33.0
      - registry1.dso.mil/ironbank/fluxcd/source-controller:v0.36.1