---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: flux-system
spec:
  chart:
    spec:
      chart: longhorn
      version: 1.4.1
      sourceRef:
        kind: HelmRepository
        name: longhorn
  interval: 10m
  targetNamespace: longhorn
  valuesFrom:
  - kind: ConfigMap
    name: longhorn-cm