cluster-init: true
write-kubeconfig-mode: "0644"

tls-san:
  - rpi-k8s-1
  - rpi-k8s-1.kellerhome.us
  - pi
  - pi.kellerhome.us
disable:
  - traefik
  - servicelb
disable-cloud-controller: true
token: my-shared-secret