nextcloud:
  extraInitContainers:
    - name: postgresql-isready
      image: bitnami/postgresql:15.3.0-debian-11-r74
      env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: nextcloud-db
              key: db-username
      command:
      - "sh"
      - "-c"
      - "until pg_isready -h ###ZARF_VAR_NEXTCLOUD_POSTGRESQL_HOST### -U ${POSTGRES_USER} ; do sleep 2 ; done"

externalDatabase:
  enabled: true

  ## Supported database engines: mysql or postgresql
  type: postgresql

  ## Use a existing secret from crunchy PGO
  existingSecret:
    enabled: false

nodeSelector:
  office: large-storage

persistence:
  storageClass: "longhorn"
  # existingClaim: "pvc-11e12470-7738-48b1-bd1c-dbd9e504553c"

  nextcloudData:
    storageClass: "local-path-storage"
