apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx
    zarf.dev/agent: ignore
  name: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
        zarf.dev/agent: ignore
    spec:
      containers:
      - image: ghcr.io/brandtkeller/image/personal-blog:latest
        imagePullPolicy: Always
        name: personal-blog
        ports:
        - containerPort: 8443
        - containerPort: 8080
        volumeMounts:
        - mountPath: /etc/nginx/ssl
          name: secret-volume
        - mountPath: /etc/nginx/conf.d
          name: configmap-volume
      volumes:
      - name: secret-volume
        secret:
          secretName: blog-brandtkeller-tls
      - name: configmap-volume
        configMap:
          name: nginx-conf
