apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: home-lab
  namespace: flux-system
spec:
  interval: 10m
  url: https://github.com/brandtkeller/home-lab.git
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: home-lab
  path: ./2-Orchestration/clusters/production
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
