apiVersion: v1
kind: Secret
metadata:
    name: aws-sec
stringData:
    config: |
        [default]
        region = ###ZARF_VAR_REGION###
        output = json
    credentials: |
        [default]
        aws_access_key_id = ###ZARF_VAR_ACCESS_KEY###
        aws_secret_access_key = ###ZARF_VAR_SECRET_ACCESS_KEY###