apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: nextcloud
spec:
  exportTo:
  - istio-system
  gateways:
  - istio-system/home
  hosts:
  - cloud.home.kellerhome.us
  http:
  - route:
    - destination:
        host: nextcloud
        port:
          number: 8080