image:
  registry: cgr.dev
  repository: chainguard/nginx
  tag: "1.23.4"
containerPorts:
  http: 80
  https: 443
service:
  type: ClusterIP
# TODO: map the configmap from wrapper to a volume/volumeMount  
# extraVolumes:
# - name: config-volume
#   configMap:
#     name: proxy-conf
#     items:
#     - key: nginx.conf
#       path: nginx.conf
# extraVolumeMounts:
# - name: config-volume
#   mountPath: /etc/nginx