apiVersion: v1
kind: ConfigMap
metadata:
  name: next-cm
  namespace: flux-system
data:
  values.yaml: |
    nextcloud:
      host: cloud.infra.kellerhome.us
      configs:
        domains.config.php: |-
          <?php
          $CONFIG = array (
            'trusted_domains' =>
              array (
              0 => 'localhost',
              1 => 'cloud.infra.kellerhome.us',
              )
          );
        overwrite.config.php: |-
          <?php
          $CONFIG = array (
            'overwriteprotocol' => 'https',
          );
    livenessProbe:
      enabled: true
      initialDelaySeconds: 15
      periodSeconds: 30
      timeoutSeconds: 10
      failureThreshold: 5
      successThreshold: 1
    readinessProbe:
      enabled: true
      initialDelaySeconds: 10
      periodSeconds: 25
      timeoutSeconds: 10
      failureThreshold: 5
      successThreshold: 1
    redis:
      enabled: true
    
    postgresql:
      enabled: true
      primary:
        persistence:
          enabled: true

    internalDatabase:
      enabled: false

    externalDatabase:
      enabled: true

      ## Supported database engines: mysql or postgresql
      type: postgresql

      ## Database name
      database: nextcloud

    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      size: 300Gi
