apiVersion: v1
kind: ConfigMap
metadata:
  name: next-cm
  namespace: flux-system
data:
  values.yaml: |
    nextcloud:
      host: cloud.infra.kellerhome.us
    livenessProbe:
      enabled: true
      initialDelaySeconds: 125
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3
      successThreshold: 1
    readinessProbe:
      enabled: true
      initialDelaySeconds: 90
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3
      successThreshold: 1
    startupProbe:
      enabled: false
      initialDelaySeconds: 60
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 30
      successThreshold: 1
    redis:
      enabled: true
    
    postgresql:
      enabled: true
      primary:
        persistence:
          enabled: true

    internalDatabase:
      enabled: false

    externalDatabase:
      enabled: true

      ## Supported database engines: mysql or postgresql
      type: postgresql

      ## Database name
      database: nextcloud

    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      size: 300Gi
