apiVersion: batch/v1
kind: CronJob
metadata:
  name: cloud-sync-cronjob
  namespace: nextcloud
spec:
  schedule: '0 8 * * *'
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 7
  jobTemplate:
    metadata:
      name: cloud-sync-cronjob
    spec:
      activeDeadlineSeconds: 28800
      template:
        spec:
          affinity:
            podAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                    - nextcloud
                topologyKey: "kubernetes.io/hostname"
          containers:
          - name: s3-sync
            image: amazon/aws-cli:2.9.12
            command:
            - /bin/sh
            - -c
            - aws s3 sync /data/data/brandtkeller s3://keller-home-dev/nextcloud/brandtkeller
            volumeMounts:
            - name: aws-creds
              mountPath: "/root/.aws"
              readOnly: true
            - name: data
              mountPath: "/data"
          volumes:
          - name: aws-creds
            secret:
              secretName: aws-sec
          - name: data
            persistentVolumeClaim:
              claimName: nextcloud-nextcloud-nextcloud-data
          restartPolicy: Never