apiVersion: v1
kind: ConfigMap
metadata:
  name: jiva-cm
  namespace: flux-system
data:
  values.yaml: |
    localpv-provisioner:
      # Disable installation of node-disk-manager components by default
      openebsNDM:
        enabled: false
      # Disable openebs-device deviceClass by default.
      deviceClass:
        enabled: false
      hostpathClass:
        reclaimPolicy: Retain

      localpv:
        basePath: "/data/volumes"
    storageClass:
      isDefaultClass: true
      reclaimPolicy: Retain
        