apiVersion: v1
kind: ConfigMap
metadata:
  name: dnsfiles
data:
  Corefile: |
    kellerhome.us:53 {
        file /etc/coredns/dns.db
        log
        errors
    }

    .:53 {
        forward . 8.8.8.8 9.9.9.9
        log
        errors
    }

  dns.db: |
    kellerhome.us.        IN  SOA dns.kellerhome.us. keller.kellerhome.us. 2015082541 7200 3600 1209600 3600
    router.kellerhome.us.                 IN  A  192.168.0.1
    prox.kellerhome.us.                   IN  A  192.168.1.8
    prox2.kellerhome.us.                  IN  A  192.168.1.10
    prox3.kellerhome.us.                  IN  A  192.168.1.9
    k3s-home-1.kellerhome.us.             IN  A  192.168.0.41
    k3s-home-2.kellerhome.us.             IN  A  192.168.0.42
    k3s-home-3.kellerhome.us.             IN  A  192.168.0.43
    home.kellerhome.us.                   IN  A  192.168.0.50
    *.home.kellerhome.us.                 IN  A  192.168.0.51
    vpn.home.kellerhome.us.               IN  A  192.168.0.52
    dns.home.kellerhome.us.               IN  A  192.168.0.53
    unifi.home.kellerhome.us.             IN  A  192.168.0.54
    manage.kellerhome.us.                 IN  A  192.168.0.130
    home.kellerhome.us.                   IN  A  192.168.0.132
    *.home.kellerhome.us.                 IN  A  192.168.0.133
  