apiVersion: v1
kind: Service
metadata:
  name: dns-lb
spec:
  selector:
    name: local-dns
  ports:
    - name: dns-tcp
      protocol: TCP
      port: 53
      targetPort: 53
    - name: dns-udp
      protocol: UDP
      port: 53
      targetPort: 53
  type: LoadBalancer