apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: rsync
  name: rsync
  namespace: nextcloud
spec:
  # specifically assigning to node manually - update to dynamic in future orchestration
  containers:
  # replace sleep with a full rsync command
  - args:
    - sleep
    - "3600"
    image: brandtkeller/rsync:8.7
    imagePullPolicy: Always
    name: rsync
    resources: {}
    volumeMounts:
    - name: data-vol
      mountPath: /data
  volumes:
  - name: data-vol
    persistentVolumeClaim:
      claimName: nextcloud-nextcloud
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
