# yaml-language-server: $schema=https://raw.githubusercontent.com/defenseunicorns/uds-cli/main/uds.schema.json
options:
   log_level: warn
   architecture: amd64
   no_log_file: false
   no_progress: true
   uds_cache: /tmp/uds-cache
   tmp_dir: /tmp/tmp_dir
   insecure: false
   oci_concurrency: 3

shared:
  domain: kellerhome.us

variables:
  metallb-package:
    metallb_interface: eth0
    metallb_ip_address_pool: 192.168.99.250-192.168.99.254