apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: valheim
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ./
      interval: 5m
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: valheim
        namespace: flux-system
      version: '*'
  install:
    remediation:
      retries: -1
  interval: 2m
  rollback:
    cleanupOnFail: true
    timeout: 10m
  targetNamespace: valheim
  test:
    enable: false
  timeout: 10m
  upgrade:
    cleanupOnFail: true
    remediation:
      remediateLastFailure: true
      retries: 3
  valuesFrom:
  - kind: ConfigMap
    name: valheim-cm
  - kind: Secret
    name: valheim-secret