---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: flux-system
spec:
  chart:
    spec:
      chart: nextcloud
      version: 3.3.4
      sourceRef:
        kind: HelmRepository
        name: nextcloud
  interval: 10m
  targetNamespace: nextcloud
  valuesFrom:
  - kind: ConfigMap
    name: next-cm
  - kind: Secret
    name: next-secret