apiVersion: v1
kind: Secret
metadata:
    creationTimestamp: null
    name: next-secret
    namespace: flux-system
stringData:
    values.yaml: ENC[AES256_GCM,data:SkHaFR6BJat3Msf0bPXjPOo3FpIScMNkZERXjUILFEMWsz4X1hUpDLxPn/PFhxdVyX0hb+fQDY+XVBwQs7zsVG8XCJ0/IfM3DoGxYfV9XZzQUQ75n1gPNmLXHkA8twD4saFMdMCvK4MSs0dtytO1/Dcg8IyIfxmCyS25ZaAaCpBqkboYQQwiEoRGjGZ6nQXLl2RgZEvzs7tI+fzhj4QqStUMlF240jYe+T9lbdC/u9ynEZ4TbFWLPX2ehb8bf9juig6jiEedqvvELNO2NTUKql1qKXpC9wy2lQJ5zILgxUdtx6S/NA5adEYvpegNpTXKDYWjTOp7O8BcZWlO7DI3+dTLXbYWUj/JG9v4cTylwaT9EFOg+l+I6txitFDksA73SQVdFFFeRmU7WHYpieY859e91Nq49gAfrHNNzN1qwclCtzjrsiTQJft5Wk3FLrZRgvzNodNXDCaw8DelEJBaOh/PxCNAKdlWCWslN+/5kL/T8UB+Hyo/UWVWbqxa2fyM3InSocNervngs5iuatKwwTlAYkGd67S2NuNtaHTGgXixyr0A,iv:hSBMPxWVu2Md7rz7fJ+iu9cNPj7WW1bR1mWgCGDuuko=,tag:vULfm1x+kK0EZ4v5ctjbzA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-12-22T18:03:42Z"
    mac: ENC[AES256_GCM,data:ImqqqpnGIGuRavmYKh6tC+aCJ+HM37narjJT4t2IBcTupmfQNSiLcflr3l9CfD6JfDFh1EDWNKn6MHuOdSEnkoBNto/BanuWxbkypGlRJFEDfN0L6EAL1cFPmreexqVJKrky+k9y90YKcKj4cdIe5EKPfT1euid+IA025c+1IYU=,iv:4/G1ckS+JcITVIF9MekJFJlku5VW2jSr4N5f6bfREr0=,tag:TJ30FNhUqUQkhnINKBwJ+g==,type:str]
    pgp:
        - created_at: "2022-12-22T18:03:41Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA1pyIBzTsoKaAQ//d7rlIrGUw8UfMq/FQxCHrkMUM9ErKpc+5BHH0v+Rjqt8
            LwT1UgF8v9ZWWHMLQWG2NjSOzRglWBIvZa5mbGoxM7IkySlYwUwOziAzj2cX4i7z
            NO4FvyQ8IDSk7rzGJlgnsTjsx1aeflEB2LuyiztKRmAK4gOGwjNgAAwESI+qYUT6
            SRDqXG8FkaL58ASamBmxAGRPm5WJJ+nZurUi0eE4nlrTVbUOODIMyi9KqH0cMGLf
            v+5H52CH0OiEmJ1pzbszxfIhaKXQRqFcpe9burElX/9RhUxmakvmxwuVpl0F5WWT
            9/pjyKCzhq1ZiZXFbI33fAotchUYpJmaLWmmhg+Hr3eQvggxZiB6UoS9eRHedoyu
            U9ETTuHCuZMOPJTD0PqrtxCZPZILYgOozWOYhF0q+KakuKhkpJHm4NaaybZqXxPD
            EEwo4P6deCi+LOp7T0i12CjhURfRHTadBoiuSmnPwPFt7exW5PMXBOkH3tJDsVdL
            kXq7yvikX3ZDHmTBlS2J+XUpEp+9IWI6ML2sNpnJq7gMYddjuDLe4Y+g6bFFkjrM
            ynbQUKrNFhP/WnaWGyM7TMv6JS0xv/5kAa52b89AecUzJQRHM/Cf/IF/rWbSUw+9
            0t83Z6ejHpzjqW4udb6Ta8suZNCVVwuu3eGQaIGUB1YYo0yylQ2hA7lUweI9J9fS
            XgHOsm9mtCKDsrO0MseVT/ZVcYnYuuO4m+ChgHD96xoDqgKimbyCExsA0hT749sU
            ++RgxOIje4ah/T6UHlBqel8emrboMvz2QL0+e7ZnFODsOy4xe1FpcbLVDTbNJZY=
            =pvCe
            -----END PGP MESSAGE-----
          fp: BA7A548FFD17E767752D71D7D1415DC3F01E3E5F
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
