# example manifest - does not currently do anything

## Core & Common identifying information
distro: rke2
version: v1.28.3+rke2r2
arch: amd64
airgap: true # this is assumed for now
# artifacts: 

## Individual Node Configuration
nodes:
  - address: 192.168.0.11
    user: server
    role: server
    primary: true
    local: false
    ssh_key_path: ~/.ssh/nopass
    ## Pass config file wholesale
    config: |
      write-kubeconfig-mode: "0644"

      tls-san:
        - k8s-home-1
        - k8s-home-1.kellerhome.us
        - home
        - home.kellerhome.us
      disable:
        - rke2-ingress-nginx
        - rke2-metrics-server
      disable-cloud-controller: true
      token: my-shared-secret
      node-taint:
        - "CriticalAddonsOnly=true:NoExecute"
  - address: 192.168.0.12
    user: server
    role: server
    primary: false
    local: false
    ssh_key_path: ~/.ssh/nopass
    ## Pass config file wholesale
    config: |
      server: https://192.168.0.11:9345
      write-kubeconfig-mode: "0644"

      tls-san:
        - k8s-home-2
        - k8s-home-2.kellerhome.us
        - home
        - home.kellerhome.us
      disable:
        - rke2-ingress-nginx
        - rke2-metrics-server
      disable-cloud-controller: true
      token: my-shared-secret
      node-taint:
        - "CriticalAddonsOnly=true:NoExecute"
  - address: 192.168.0.13
    user: server
    role: server
    primary: false
    local: false
    ssh_key_path: ~/.ssh/nopass
    ## Pass config file wholesale
    config: |
      server: https://192.168.0.11:9345
      write-kubeconfig-mode: "0644"

      tls-san:
        - k8s-home-3
        - k8s-home-3.kellerhome.us
        - home
        - home.kellerhome.us
      disable:
        - rke2-ingress-nginx
        - rke2-metrics-server
      disable-cloud-controller: true
      token: my-shared-secret
      node-taint:
        - "CriticalAddonsOnly=true:NoExecute"
  - address: 192.168.0.14
    user: server
    role: agent
    primary: false
    local: false
    ssh_key_path: ~/.ssh/nopass
    ## Pass config file wholesale
    config: |
      server: https://192.168.0.11:9345
      token: my-shared-secret
