apiVersion: v1
kind: ConfigMap
metadata:
  name: dnsfiles
  namespace: dns
data:
  Corefile: |
    kellerhome.us:53 {
        file /etc/coredns/dns.db
        log
        errors
    }

    .:53 {
        forward . 8.8.8.8 9.9.9.9
        log
        errors
    }

  dns.db: |
    kellerhome.us.        IN  SOA dns.kellerhome.us. keller.kellerhome.us. 2015082541 7200 3600 1209600 3600
    router.kellerhome.us.                 IN  A  192.168.0.1
    prox.kellerhome.us.                   IN  A  192.168.1.8
    prox2.kellerhome.us.                  IN  A  192.168.1.10
    prod.kellerhome.us.                   IN  A  192.168.1.20
    *.k8s.kellerhome.us.                  IN  A  192.168.1.21
    *.prod.kellerhome.us.                 IN  A  192.168.1.22
    prod-server-blue.kellerhome.us.       IN  A  192.168.1.33
    prod-server-orange.kellerhome.us.     IN  A  192.168.1.34
    prod-server-red.kellerhome.us.        IN  A  192.168.1.35
    prod-agent-orange.kellerhome.us.      IN  A  192.168.1.36
    valheim.kellerhome.us.                IN  A  192.168.1.30    
    manage.kellerhome.us.                 IN  A  192.168.0.130
  