apiVersion: v1
kind: ConfigMap
metadata:
  name: dnsfiles
  namespace: dns
data:
  Corefile: |
    kellerhome.us:53 {
        file /etc/coredns/dns.db
        log
        errors
    }

    .:53 {
        forward . 8.8.8.8 9.9.9.9
        log
        errors
    }

  dns.db: |
    kellerhome.us.        IN  SOA dns.kellerhome.us. keller.kellerhome.us. 2015082541 7200 3600 1209600 3600
    router.kellerhome.us.                 IN  A  192.168.0.1
    prox.kellerhome.us.                   IN  A  192.168.1.8
    prox2.kellerhome.us.                  IN  A  192.168.1.10
    infra.kellerhome.us.                  IN  A  192.168.1.20
    *.infra.kellerhome.us.                IN  A  192.168.1.21
    infra-server-blue.kellerhome.us.      IN  A  192.168.1.23
    infra-server-orange.kellerhome.us.    IN  A  192.168.1.24
    infra-server-red.kellerhome.us.       IN  A  192.168.1.25
    infra-agent-red.kellerhome.us.        IN  A  192.168.1.26
    infra-agent-blue.kellerhome.us.       IN  A  192.168.1.27
    infra-agent-orange.kellerhome.us.     IN  A  192.168.1.28
    valheim.kellerhome.us.                IN  A  192.168.1.30    
    manage.kellerhome.us.                 IN  A  192.168.0.130
  