apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: local-dns
  namespace: dns
spec:
  selector:
    matchLabels:
      name: local-dns
  template:
    metadata:
      labels:
        name: local-dns
    spec:
      containers:
      - name: coredns
        image: coredns/coredns:1.10.0
        args:
        - -conf
        - /etc/coredns/Corefile
        ports:
        - containerPort: 53
          hostPort: 53
          protocol: UDP
        - containerPort: 53
          hostPort: 53
          protocol: TCP
        volumeMounts:
        - mountPath: /etc/coredns
          name: config-volume
      volumes:
      - name: config-volume
        configMap:
          defaultMode: 420
          items:
          - key: Corefile
            path: Corefile
          - key: dns.db
            path: dns.db
          name: dnsfiles
